### ISSUE TITLE
Assertion error when try to use the Adj_Spearman_6P.mat for Co-expression

### ISSUE THREAD

**Issue by YoonhoWong** [RicardoRamirez2020/GCN_Cancer#2]
PPI works all fine, but I got Assertion error when I try to reproduce Co-expression model result.
I change the size from 4444 to 3866. Could you give me more information on how to fix this?

`Traceback (most recent call last):
  File ".\PPI.py", line 89, in <module>
    Train_Data = coarsening.perm_data(Train_Data, perm)
  File "..\lib\coarsening.py", line 241, in perm_data
    assert Mnew >= M
AssertionError
`

**Comment by mobinahdvfr** [comment]
i'm getting lots of errors
the google drive link in the project gives 404 error ...


and also do you know where is this data coming from?
Data = sio.loadmat('C:/Users/RJ/Desktop/exp_fpkm_pancan/processed/Final/Data/Block_PPIA.mat')
